### ISSUE TITLE
Key-length error

### ISSUE THREAD

**Issue by ThePiachu** [tyler-smith/go-bip32#3]
Recently during testing we noticed a weird error with the package - sometimes the length of the returned Key was shorter than 32. Here is an example of how to get such a key: https://github.com/FactomProject/go-bip44/commit/fd672f46ddc35bb381f497f7b64c9cf34f9e0703

It turns out the way private keys were added didn't take into account that bigInt.Bytes() truncates leading zeroes. After fixing that, it also turned out that the code checking whether a private key is valid was wrong - it tried to decode the key as a varint, meaning any leading zero was considered invalid. I assumed the code was supposed to remove any private key that was ALL zeroes. A key length checker was also implemented: https://github.com/FactomProject/go-bip32/commit/4eb323961517583391d1ce0fa403a3f63704e728

Feel free to pull in the changes.

**Comment by tyler-smith** [comment]
Thanks for making and sharing these fixes!

**Comment by lrvick** [comment]
@tyler-smith Any interest in merging this in? Seems like a reasonable fix.

**Comment by tyler-smith** [comment]
@lrvick and others, sorry for the delay. I've merged this.
